### ISSUE TITLE
"spawn EACCES" error

### ISSUE THREAD

**Issue by ADmad** [calvinbaart/vscode-phpstan#2]
After installing the plugin upon opening a php file I get the following errors in "Developer Tools"

![phpstan](https://user-images.githubusercontent.com/142658/37081762-79b02d46-2210-11e8-804a-dc034731c6b0.png)

Please let me know how I can provide more info to debug the issue.

**Comment by calvinbaart** [comment]
Should be fixed in https://github.com/calvinbaart/vscode-phpstan/commit/eff7eb153560869704933d74b591651304c75c95

We now check if we are allowed to execute phpstan.
