### ISSUE TITLE
TypeError: Cannot read property 'fsPath' of undefined

### ISSUE THREAD

**Issue by beosiris** [calvinbaart/vscode-phpstan#8]
I'm getting this exception on executing the command: "PHPScan: Scan for errors"
I'm using:
VS Code 1.24.1

I've install phpstan with that command line: composer global require phpstan/phpstan
I'm using default configuration of your module.

> [2018-07-20 10:34:26.209] [exthost1] [error] TypeError: Cannot read property 'fsPath' of undefined
> 	at PHPStan._command.vscode_1.commands.registerCommand (C:\Users\easypara\.vscode\extensions\calsmurf2904.vscode-phpstan-0.1.8\out\phpstan.js:22:30)
> 	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:697:706)
> 	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:698:212)
> 	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:87)
> 	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:779)
> 	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:851)
> 	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:620)
> 	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
> 	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
> 	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
> 	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
> 	at u (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
> 	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
> 	at emitOne (events.js:96:13)
> 	at Socket.emit (events.js:191:7)
> 	at readableAddChunk (_stream_readable.js:178:18)
> 	at Socket.Readable.push (_stream_readable.js:136:10)
> 	at Pipe.onread (net.js:560:20) extension.scanForErrors

I can launch phpstan manually and it work without getting a fatal error:
![image](https://user-images.githubusercontent.com/1056334/42993275-3e06526a-8c0b-11e8-9f72-88d30bd5391a.png)

**Comment by calvinbaart** [comment]
Fixed in the upcoming version. As a temporary workaround try using the command from the right-click menu on files/folders instead of the global command

**Comment by bdenizar** [comment]
Closing
